config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/IM-sqaaas-test:
      branch: master
      repo: https://github.com/orviz/IM-sqaaas-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  SvcQC.Dep:
    repos:
      github.com/orviz/IM-sqaaas-test im_client:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-buff-frigatebird.sh
        container: svcqc.dep_gummy-grey-caiman
timeout: 600
